version: '3.8'

services:
  go-sdk:
    container_name: go
    image: go-sdk:1.21.5
    volumes:
      - type: volume
        source: go
        target: /app
      - type: bind
        source: /home/hajsf/Development/go
        target: /app
    ports:
      - 4040:80
    command: tail -f /dev/null
volumes:
  go:
#    external: true # If the mojo volume already exists