version: '3.8'

services:
  nicegui-sdk:
    container_name: nicegui
    image: nicegui:v1.4.6
    volumes:
      - type: volume
        source: nicegui
        target: /app
      - type: bind
        source: /home/hajsf/Development/nicegui
        target: /app
    ports:
      - 4040:80
    command: tail -f /dev/null
volumes:
  nicegui:
#    external: true # If the mojo volume already exists