version: '3.8'

services:
  python-sdk:
    container_name: python
    image: python-sdk:v3.11.7
    volumes:
      - type: volume
        source: python
        target: /app
      - type: bind
        source: /home/hajsf/Development/python
        target: /app
    ports:
      - 4040:80
    command: tail -f /dev/null
volumes:
  python:
#    external: true # If the mojo volume already exists