version: '3.8'

services:
  python-sdk:
    container_name: python
    image: python-sdk:v3.11.7
    volumes:
#      - /home/hajsf/Development/python:/root
      - python:/root
    ports:
      - 4043:80
volumes:
  python:
#    external: true # If the python volume already exists
#    command: tail -f /dev/null