version: '3.8'

services:
  zig-sdk:
    container_name: zig
    image: zig-sdk:0.12.0-dev
    volumes:
      - type: volume
        source: zig
        target: /app
      - type: bind
        source: /home/hajsf/Development/zig
        target: /app
    ports:
      - 4040:80
    command: tail -f /dev/null
volumes:
  zig:
#    external: true # If the zig volume already exists

