version: '3.8'
services:
  my-service:
    container_name: mojo
    image: docker.io/hajsf/mojo-sdk:r0.6
    volumes:
      - type: volume
        source: mojo
        target: /app
      - type: bind
        source: /home/hajsf/Development/mojo
        target: /app
    ports:
      - 4040:80
    command: tail -f /dev/null
volumes:
  mojo:
#    external: true # If the mojo volume already exists
